version: '3.8'

services:
  postgres:
    image: postgres:16-16-alpine
    container_name: paw_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: paw_renovations
    ports:
      -"5432":"5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
  volumes:
    pgdata: