/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRenovationsIdRouteImport } from './routes/admin/renovations/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRenovationsIdRoute = AdminRenovationsIdRouteImport.update({
  id: '/admin/renovations/$id',
  path: '/admin/renovations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/renovations/$id': typeof AdminRenovationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/renovations/$id': typeof AdminRenovationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/renovations/$id': typeof AdminRenovationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/renovations/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/renovations/$id'
  id: '__root__' | '/' | '/admin/renovations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRenovationsIdRoute: typeof AdminRenovationsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/renovations/$id': {
      id: '/admin/renovations/$id'
      path: '/admin/renovations/$id'
      fullPath: '/admin/renovations/$id'
      preLoaderRoute: typeof AdminRenovationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRenovationsIdRoute: AdminRenovationsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
